In [1]:
import pandas as pd
import numpy as np
import pickle
from SentimentFeatureGenerator import *
from TfidfFeatureGenerator import *
from SvdFeatureGenerator import *
from Word2VecFeatureGenerator import *
from CountFeatureGenerator import *

In [2]:
with open('related_data.pkl','rb') as infile:
    related_data = pickle.load(infile)
    print('related_data loaded, the shape is ', related_data.shape)

related_data loaded, the shape is  (13427, 11)


### Sentiment Feature

In [3]:
sentiFG = SentimentFeatureGenerator()

In [4]:
headlineSenti, bodySenti = sentiFG.process(related_data)

generating sentiment features
for headline
headlineSenti.shape: (13427, 4)
headline sentiment features of dataset saved in train.headline.senti.pkl
headine senti done
for body
bodySenti.shape: (13427, 4)
body sentiment features of dataset saved in train.body.senti.pkl


In [4]:
headlineSenti, bodySenti = sentiFG.read()

headlineSenti.shape: (13427, 4)
bodySenti.shape: (13427, 4)


In [7]:
headlineSenti

array([[ 0.    ,  0.    ,  1.    ,  0.    ],
       [ 0.    ,  0.    ,  1.    ,  0.    ],
       [-0.6249,  0.267 ,  0.733 ,  0.    ],
       ...,
       [-0.5106,  0.281 ,  0.719 ,  0.    ],
       [-0.5267,  0.355 ,  0.645 ,  0.    ],
       [-0.0516,  0.091 ,  0.909 ,  0.    ]])

In [8]:
bodySenti

array([[-0.20880588,  0.08      ,  0.885     ,  0.03488235],
       [ 0.11378286,  0.03011429,  0.901     ,  0.06888571],
       [-0.289575  ,  0.14115   ,  0.77945   ,  0.02945   ],
       ...,
       [-0.29746316,  0.10942105,  0.86442105,  0.02615789],
       [-0.1808    ,  0.158     ,  0.728     ,  0.115     ],
       [-0.00757143,  0.03528571,  0.86414286,  0.10057143]])

### Tf-idf Feature

In [5]:
tfidfFG = TfidfFeatureGenerator()

In [4]:
xHeadlineTfidf, xBodyTfidf, simTfidf = tfidfFG.process(related_data)

xHeadlineTfidf.shape: (13427, 465091)
headline tfidf features of data set saved in train.headline.tfidf.pkl
xBodyTfidf.shape: (13427, 465091)
body tfidf features of data set saved in train.body.tfidf.pkl
simTfidf.shape: (13427, 1)
tfidf sim. features of data set saved in train.sim.tfidf.pkl


In [6]:
xHeadlineTfidf, xBodyTfidf, simTfidf = tfidfFG.read()

xHeadlineTfidf.shape: (13427, 465091)
xBodyTfidf.shape: (13427, 465091)
simTfidf.shape: (13427, 1)


In [7]:
xHeadlineTfidf

<13427x465091 sparse matrix of type '<class 'numpy.float64'>'
	with 294456 stored elements in Compressed Sparse Row format>

In [8]:
xBodyTfidf

<13427x465091 sparse matrix of type '<class 'numpy.float64'>'
	with 7687948 stored elements in Compressed Sparse Row format>

In [9]:
simTfidf

array([[0.21916453],
       [0.08369312],
       [0.48043096],
       ...,
       [0.11251515],
       [0.21891469],
       [0.22920424]])

### SVD Feature

In [7]:
svdFG = SvdFeatureGenerator()

In [13]:
xHeadlineSvd, xBodySvd, simSvd = svdFG.process(related_data)

xHeadlineTfidf.shape: (13427, 465091)
xBodyTfidf.shape: (13427, 465091)
simTfidf.shape: (13427, 1)
xHeadlineTfidf.shape: (13427, 465091)
xHeadlineSvd.shape: (13427, 50)
headline svd features of data set saved in train.headline.svd.pkl
xBodySvd.shape: (13427, 50)
body svd features of training set saved in train.body.svd.pkl
simSvd.shape: (13427, 1)
svd sim. features of data set saved in train.sim.svd.pkl


In [8]:
xHeadlineSvd, xBodySvd, simSvd = svdFG.read()

xHeadlineSvd.shape: (13427, 50)
xBodySvd.shape: (13427, 50)
simSvd.shape: (13427, 1)


In [15]:
xHeadlineSvd

array([[ 0.00946175,  0.0050689 ,  0.00026978, ..., -0.00184472,
        -0.00064748,  0.0021689 ],
       [ 0.00725327,  0.00672148,  0.00453269, ..., -0.00411231,
         0.01424235, -0.01555256],
       [ 0.02290207,  0.0099219 ,  0.00556221, ..., -0.0085098 ,
        -0.00273058,  0.00461319],
       ...,
       [ 0.01377683,  0.01030005,  0.00608008, ..., -0.01475132,
        -0.03156204,  0.09696381],
       [ 0.03616258,  0.01792806,  0.00502755, ...,  0.01937278,
        -0.00843153, -0.01184159],
       [ 0.074275  , -0.0032135 ,  0.00769897, ..., -0.00488338,
        -0.01665699, -0.00237974]])

In [16]:
xBodySvd

array([[ 0.03470985,  0.0165338 ,  0.00626395, ...,  0.00180585,
         0.0014676 , -0.0014639 ],
       [ 0.05791692,  0.04302227,  0.0225927 , ...,  0.00610377,
         0.03707987, -0.06138535],
       [ 0.03560127,  0.01844605,  0.00723456, ..., -0.0029751 ,
        -0.00315884,  0.00269786],
       ...,
       [ 0.05445808,  0.03474754,  0.02245391, ..., -0.03344893,
        -0.05388869,  0.17474985],
       [ 0.02843657,  0.01098039,  0.00488299, ...,  0.0212003 ,
         0.00831135, -0.01016702],
       [ 0.06298217,  0.01776889,  0.01972082, ..., -0.00737732,
        -0.00059831,  0.00025636]])

In [17]:
simSvd

array([[0.67881047],
       [0.96043358],
       [0.92683648],
       ...,
       [0.97444611],
       [0.98837432],
       [0.92934904]])

### Word2Vec Feature

In [9]:
word2vecFG = Word2VecFeatureGenerator()

In [4]:
headlineVec, bodyVec, simVec = word2vecFG.process(related_data)

generating word2vec features
model loaded
Headline_unigram_array:  (13427,)
headlineVec  (13427, 300)
headline word2vec features of data set saved in train.headline.word2vec.pkl
headine done
Body_unigram_array:  (13427,)
bodyVec  (13427, 300)
body word2vec features of data set saved in train.body.word2vec.pkl
body done
simVec.shape: (13427, 1)
word2vec sim. features of data set saved in train.sim.word2vec.pkl


In [10]:
headlineVec, bodyVec, simVec = word2vecFG.read()

headlineVec.shape: (13427, 300)
bodyVec.shape: (13427, 300)
simVec.shape: (13427, 1)


In [6]:
headlineVec

array([[ 7.50404004e-02,  3.59492218e-02, -9.60042341e-05, ...,
        -5.12837163e-02,  4.00992231e-02,  1.19219803e-02],
       [ 9.30009363e-02,  6.74728992e-02, -2.34021717e-03, ...,
         3.66163289e-03, -3.15727574e-02,  7.23588591e-02],
       [ 4.94563485e-02,  3.54900092e-02,  2.47389705e-02, ...,
        -1.01362450e-01,  6.23018475e-02,  6.16364098e-04],
       ...,
       [ 1.06946061e-01,  2.25469069e-03,  4.35728569e-02, ...,
        -5.38823400e-02,  6.29824995e-02,  7.73967057e-03],
       [ 7.17788898e-02, -1.76894229e-02,  7.37191665e-02, ...,
        -1.04984853e-02,  9.00299718e-02, -7.46042050e-03],
       [-1.37780814e-02,  5.00387097e-02,  1.75331500e-02, ...,
        -4.76819626e-02,  5.50542048e-02, -4.90198838e-02]])

In [7]:
bodyVec

array([[ 0.04067834,  0.06328456,  0.03503142, ..., -0.04174063,
         0.06769959, -0.00987635],
       [ 0.03886664,  0.06263685,  0.03154274, ..., -0.05163963,
         0.04191154, -0.0214333 ],
       [ 0.03099006,  0.03090744,  0.04150776, ..., -0.06714159,
         0.04690744, -0.04100797],
       ...,
       [ 0.02614567,  0.02926969,  0.07045992, ..., -0.06479935,
         0.07556425, -0.04714514],
       [ 0.03961257,  0.01573018,  0.07511423, ..., -0.04345158,
         0.08092605, -0.05160161],
       [-0.01027013,  0.01112148,  0.02871667, ..., -0.06595363,
         0.04836444, -0.05488853]])

In [8]:
simVec

array([[0.72038103],
       [0.58138594],
       [0.87521635],
       ...,
       [0.77254695],
       [0.78604965],
       [0.77248578]])

### Basic Count Feature

In [11]:
countFG = CountFeatureGenerator()

In [4]:
xBasicCounts = countFG.process(related_data)

generate counting features
basic counting features for training saved in feature_pkl/train.basic.pkl


In [12]:
xBasicCounts = countFG.read()

feature names:  ['count_of_Headline_unigram', 'count_of_unique_Headline_unigram', 'ratio_of_unique_Headline_unigram', 'count_of_Headline_bigram', 'count_of_unique_Headline_bigram', 'ratio_of_unique_Headline_bigram', 'count_of_Headline_trigram', 'count_of_unique_Headline_trigram', 'ratio_of_unique_Headline_trigram', 'count_of_articleBody_unigram', 'count_of_unique_articleBody_unigram', 'ratio_of_unique_articleBody_unigram', 'count_of_articleBody_bigram', 'count_of_unique_articleBody_bigram', 'ratio_of_unique_articleBody_bigram', 'count_of_articleBody_trigram', 'count_of_unique_articleBody_trigram', 'ratio_of_unique_articleBody_trigram', 'count_of_Headline_unigram_in_articleBody', 'ratio_of_Headline_unigram_in_articleBody', 'count_of_Headline_bigram_in_articleBody', 'ratio_of_Headline_bigram_in_articleBody', 'count_of_Headline_trigram_in_articleBody', 'ratio_of_Headline_trigram_in_articleBody', 'len_sent_Headline', 'len_sent_articleBody', 'fake_exist', 'fraud_exist', 'hoax_exist', 'false